### ISSUE TITLE
website not working

### ISSUE THREAD

**Issue by t-900-a** [zoidbergZA/turtlecoin-tips#13]
project abandoned?

https://turtlecoin.tips/ is not allowing login

**Comment by zoidbergZA** [comment]
Hi there, the project is not currently operational. However, I am considering to reactive it based on TurtleCoin V2 after it is launched later this year. Keep an eye on the [TurtleCoin blog](https://blog.turtlecoin.lol/) for updates on the new version of TurtleCoin!

I have updated the website landing page to remove the login buttons in the meantime to clarify that the app is not currently active.
